abbr c "cargo"
abbr cb "cargo build"
abbr cbr "cargo build --release"
abbr ccl "cargo clippy"
abbr cn "cargo new"
abbr cnl "cargo new --lib"
abbr cr "cargo run"
abbr crq "cargo run -q"
abbr crr "cargo run --release"
abbr ct "cargo test"
abbr ctq "cargo test -q"
abbr e "nvim"
abbr gPP "git pull"
abbr gPr "git pull --rebase"
abbr ga "git add"
abbr gaa "git add -A"
abbr gap "git add --patch"
abbr gb "git branch"
abbr gba "git branch -a"
abbr gc "git commit"
abbr gc! "git commit --amend"
abbr gc!! "git commit --amend --no-edit"
abbr gch "git checkout"
abbr gchb "git checkout -b"
abbr gcm "git commit -m"
abbr gcp "git cherry-pick"
abbr gcpa "git cherry-pick --abort"
abbr gcpc "git cherry-pick --continue"
abbr gd "git diff"
abbr gD "git diff --cached"
abbr gff "git fetch"
abbr gfa "git fetch --all"
abbr gfp "git fetch --prune"
abbr gll "git log"
abbr glo "git log --oneline"
abbr gmm "git merge"
abbr gma "git merge --abort"
abbr gmc "git merge --continue"
abbr gpa "git push --all"
abbr gpf "git push --force"
abbr gpp "git push"
abbr gra "git rebase --abort"
abbr grc "git rebase --continue"
abbr gri "git rebase -i"
abbr grr "git rebase"
abbr gs "git status"
abbr gsh "git show"
abbr gst "git stash"
abbr gsta "git stash apply"
abbr gstl "git stash list"
